source 'https://rubygems.org'

ruby '2.1.3'
#ruby-gemset=cie_global

group :global do
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
  gem 'rails', '4.0.0'

# Use sqlite3 as the database for Active Record
  gem 'sqlite3'

# Mysql Adapter
  gem 'mysql2'

  gem "activerecord-import", ">= 0.5.0"
# Common Gateway Interface protocol
#gem 'cgi'

# Awesome XML parser.

  gem 'nokogiri', '1.6.0' # Since it fails on Mac due to libiconv. You can try new version

end



